### Get User Data
GET http://localhost:5001/apisirs/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWEiOiJpbmF5IiwiZW1haWwiOiJpbmF5QGdtYWlsLmNvbSIsInJzSWQiOiIxIiwiaWF0IjoxNjczMzM2NzY0LCJleHAiOjE2NzMzMzY3OTl9.OlIsHubSol7JZjcOxQR7m4JzF_NJUR96v0DxKTQ5bgw

### Get Token
GET http://localhost:5001/apisirs/token


### RL 3.7 READ
GET http://localhost:5001/apisirs/surveikepuasan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU2LCJuYW1hIjoiUlMgVW11bSBEYWVyYWggVGFsYW5nIFViaSIsImVtYWlsIjoiMTYwMzA4NSIsInJzSWQiOiIxNjAzMDg1IiwiaWF0IjoxNjc2OTQ0OTA1LCJleHAiOjE2NzY5NDQ5NDB9.Z3ippDvMy0sd05ZFJ13rmH6fljbInR5upOKkiVQznwY

### Login
POST http://localhost:5001/apisirs/logina
Content-Type: application/json

{
    "userName": "1603085",
    "password": "12345"
}

###survei
POST  http://localhost:5001/apisirs/surveikepuasan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU2LCJuYW1hIjoiUlMgVW11bSBEYWVyYWggVGFsYW5nIFViaSIsImVtYWlsIjoiMTYwMzA4NSIsInJzSWQiOiIxNjAzMDg1IiwiaWF0IjoxNjc2OTQ0NTk2LCJleHAiOjE2NzY5NDQ2MzF9.0sJjqqBLaFVGuConcMGuk_bhRMIBt-1xJetKRlzrl8U

{
        "noRekamMedis": "12",
        "nama": "Budi",
        "tanggalLahir": "2022-01-01",
        "umur": 23,
        "jenisKelamin": "AO01",
        "pendidikanTerakhir": "AO01",
        "pekerjaanUtama": "AO01",
        "debitur": "AO01",
        "noHp": "08222222222",
        "rekomendasi": "AO01",
        "kritikSaran": "Tes",
        
    "data": [
       
        {
                    "pertanyaanId": 1,
                    "jawabanId": "AO01"
                    
                    
        },
        {
                    "pertanyaanId": 2,
                    "jawabanId": "AO04"
                    
                    
        }
    ]
}