### Get User Data
GET http://202.70.136.86/apisurveikepuasanpelanggan/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWEiOiJpbmF5IiwiZW1haWwiOiJpbmF5QGdtYWlsLmNvbSIsInJzSWQiOiIxIiwiaWF0IjoxNjczMzM2NzY0LCJleHAiOjE2NzMzMzY3OTl9.OlIsHubSol7JZjcOxQR7m4JzF_NJUR96v0DxKTQ5bgw

### Get Token
GET http://202.70.136.86/apisurveikepuasanpelanggan/token



### Get data Survei ORM
GET http://202.70.136.86/apisurveikepuasanpelanggan/surveikepuasan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU2LCJuYW1hIjoiUlMgVW11bSBEYWVyYWggVGFsYW5nIFViaSIsImVtYWlsIjoiMTYwMzA4NSIsInJzSWQiOiIxNjAzMDg1IiwiaWF0IjoxNjc2OTcyMzA5LCJleHAiOjE2NzY5NzIzNDR9.dbD2foUyyVNd3YCMTwZANU24J-eYpuWu506t1jpWP0w

### Login
POST http://202.70.136.86/apisurveikepuasanpelanggan/login
Content-Type: application/json

{
    "userName": "3374010",
    "password": "12345"
}

### Get Data Survei SQL
GET http://202.70.136.861/apisurveikepuasanpelanggan/getdatasurveikepuasanpelanggan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU2LCJuYW1hIjoiUlMgVW11bSBEYWVyYWggVGFsYW5nIFViaSIsImVtYWlsIjoiMTYwMzA4NSIsInJzSWQiOiIxNjAzMDg1IiwiaWF0IjoxNjc3MDI3MzY4LCJleHAiOjE2NzcwMjc0MDN9.dUNzO0-ZDY_7lz5yf2Qie1h87Aybd_UelAwCUGKk0H8

### Input Survei
POST  http://202.70.136.86/apisurveikepuasanpelanggan/surveikepuasanpelanggan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjU2LCJuYW1hIjoiUlMgVW11bSBEYWVyYWggVGFsYW5nIFViaSIsImVtYWlsIjoiMTYwMzA4NSIsInJzSWQiOiIxNjAzMDg1IiwiaWF0IjoxNjc2OTcyMjY0LCJleHAiOjE2NzY5NzIyOTl9.Q-w_kjPybac47Ni7GJ4_7N6pZseumz2WYICIm-g9Fwk

{
        "noRekamMedis": "12",
        "nama": "Budi",
        "tanggalLahir": "2022-01-01",
        "umur": 23,
        "jenisKelamin": "AO01",
        "pendidikanTerakhir": "AO01",
        "pekerjaanUtama": "AO01",
        "debitur": "AO01",
        "noHp": "08222222222",
        "rekomendasi": "AO01",
        "kritikSaran": "Tes",
        
    "data": [
       
        {
                    "pertanyaanId": 1,
                    "jawabanId": "AO01"
                    
                    
        },
        {
                    "pertanyaanId": 2,
                    "jawabanId": "AO04"
                    
                    
        }
    ]
}